# These are specific configuration settings required for travis-ci
# see http://travis-ci.org/tardate/noagenda_dashboard
rvm: 1.9.2
script: "bundle exec rake db:drop db:create db:migrate spec"
env:
  - DB=postgresql
